Repository FRONTENDSCHOOL6/finalize-react-6, pull requests merged in 2023-09, with the labels that each got.

#31 react: helmet title 추가
  src/pages/Home.jsx
  src/pages/MyProfile.jsx
Labels: 💻React

#37 feat: 헤더 fixed 메인 페이지에만 되도록 구현
  src/layout/Header.jsx
Labels: 💻CSS, 💻React

#38 [html/css] 콘텐츠 페이지 마크업/스타일링 완료
  src/assets/card1.png
  src/components/PageHead.jsx
  src/components/content/ContentInput.jsx
  src/components/content/ContentItem.jsx
  src/components/content/ContentTitle.jsx
  src/pages/Contents.jsx
  src/pages/content/ContentCreate.jsx
  src/pages/content/ContentDetail.jsx
  src/styles/tailwind.css
  tailwind.config.js
Labels: 💻HTML, 💻CSS

#61 markup: join 마크업 수정
  src/components/Button.jsx
  src/pages/Join.jsx
Labels: 💻HTML, 💻CSS

#62 [react] 콘텐츠 수정 상세 페이지 수정 및 기능 추가
  src/components/PageHead.jsx
  src/components/content/CommentItem.jsx
  src/pages/content/ContentCreate.jsx
  src/pages/content/ContentDetail.jsx
Labels: 💻React, 💻기능추가

#64 feat: 카카오 맵 api
  src/components/GetKakaoMap.jsx
  src/pages/TrafficInfo.jsx
Labels: 💻API

#66 [기능 구현] 콘텐츠 등록 페이지 - 카카오맵, 태그
  index.html
  src/components/Map.jsx
  src/components/content/TagSelect.jsx
  src/pages/Contents.jsx
  src/pages/content/ContentCreate.jsx
  src/pages/content/ContentDetail.jsx
  src/styles/map.css
Labels: 💻React, 💻API

#67 feat: 교통 정보 표시 기능 추가
  src/components/GetKakaoMap.jsx
  src/pages/TrafficInfo.jsx
Labels: 💻React, 💻API

#68 [기능 구현] 콘텐츠 페이지 생성, 상세, 목록 작업
  src/App.jsx
  src/components/Map.jsx
  src/components/ShowMap.jsx
  src/components/content/ContentItem.jsx
  src/components/content/colorStyles.jsx
  src/components/content/data/data.jsx
  src/layout/Header.jsx
  src/pages/Contents.jsx
  src/pages/content/ContentCreate.jsx
  src/pages/content/ContentDetail.jsx
  src/styles/map.css
Labels: 💻React, 💻기능추가, 💻API

#69 날씨 페이지, 메인 페이지 기능 구현
  public/mainSlide2.jpeg
  public/mainSlide3.jpeg
  public/pause.png
  public/play.png
  src/components/MainContent.jsx
  src/components/MainSlide.jsx
  src/components/MainTag.jsx
  src/components/weather/OnedayWeather2.jsx
  src/components/weather/ThreedaysWeather.jsx
  src/components/weather/ThreedaysWeatherTable.jsx
  src/components/weather/WeatherTable2.jsx
  src/pages/Home.jsx
  src/pages/WeatherInfo.jsx
Labels: 💻React, 💻API

#70 [날씨 페이지] 문구 수정 및 현재 위치 보여주기
  src/components/weather/SelectLocation.jsx
  src/pages/WeatherInfo.jsx
Labels: 💻CSS, 💻React

#73 [React] 콘텐츠 목록, 생성, 헤더
  src/components/ShowMap.jsx
  src/layout/Header.jsx
  src/layout/RootLayout.jsx
  src/pages/Contents.jsx
  src/pages/content/ContentCreate.jsx
  src/pages/content/ContentDetail.jsx
  src/routes.jsx
Labels: 💻React, 💻기능추가, 💻API

#75 design: 상세 페이지 커스텀 태그 보이기
  src/pages/content/ContentDetail.jsx
Labels: 💻CSS

#76 메인 페이지 슬라이드 이미지 변경 및 로그인 인증 페이지 수정
  src/components/MainSlide.jsx
  src/routes.jsx
Labels: 💻React

#77 로딩 스피너, 메인 페이지 framer motion 기능 구현
  src/components/MainContent.jsx
  src/components/MainTag.jsx
  src/components/Spinner.jsx
  src/components/weather/GetWeather.jsx
  src/components/weather/ImgSky.jsx
  src/components/weather/OnedayWeather.jsx
  src/components/weather/ThreedaysWeather.jsx
  src/components/weather/WeatherTable.jsx
  src/pages/Home.jsx
Labels: 💻CSS, 💻React

#80 [기능 구현] 카카오 로그인/로그아웃, 유저 로그인 상태 유지
  src/components/login/KakaoLogin.jsx
  src/components/login/LoginPageContent.jsx
  src/layout/Header.jsx
  src/pages/Join.jsx
  src/pages/Login.jsx
  src/pages/finduser/FindId.jsx
  src/pages/finduser/FindPw.jsx
  src/routes.jsx
  src/store/useAuthStore.js
Labels: 💻React, 💻기능추가, 💻API

#82 이미지 추가 및 콘텐츠 목록 정렬
  public/jejulogo.png
  src/assets/rightWhite.svg
  src/components/content/ContentItem.jsx
  src/pages/Contents.jsx
  src/pages/content/ContentDetail.jsx
  src/styles/tailwind.css
Labels: 💻React, 💻기능추가

#83 feat: 전체 동의, 체크 후 가입 버튼 활성화 기능 구현
  src/components/Button.jsx
  src/components/InputField.jsx
  src/components/KakaoMap/GetKakaoMap.jsx
  src/components/login/Termscheck.jsx
  src/components/modal/Modal.jsx
  src/components/modal/TermsOfService.jsx
  src/pages/Join.jsx
  src/pages/Login.jsx
  src/pages/TrafficInfo.jsx
Labels: 💻React, 💻기능추가

#85 fix: 약관을 동의하지 않았을 때 가입 기능 오류 수정
  src/components/InputField.jsx
  src/components/join/Modal.jsx
  src/components/join/TermsOfService.jsx
  src/components/join/Termscheck.jsx
  src/pages/Join.jsx
Labels: 💻React, 💻기능추가

#86 [기능 구현] 콘텐츠 등록/수정/삭제
  src/pages/content/ContentCreate.jsx
  src/pages/content/ContentDetail.jsx
  src/pages/content/ContentEdit.jsx
  src/routes.jsx
  src/store/useAuthStore.js
Labels: 💻React, 💻기능추가

#87 목록 페이지네이션 정밀화, 지도 상태 관리 적용 등
  src/components/MainTag.jsx
  src/components/Map.jsx
  src/components/ShowMap.jsx
  src/components/content/ContentItem.jsx
  src/layout/RootLayout.jsx
  src/pages/Contents.jsx
  src/pages/Home.jsx
  src/store/useMapStore.js
Labels: 💻React, 💻기능추가

#88 댓글 입력 후 서버에 등록되도록 했습니다
  src/components/content/AddComment.jsx
  src/pages/content/ContentDetail.jsx
Labels: 💻React, 💻기능추가

#89 [기능 구현] 로그인 시 유저 정보 수정 및 프로필 페이지 작업 세팅, 헤더 수정 등
  src/layout/Header.jsx
  src/pages/Login.jsx
  src/pages/MyProfile.jsx
  src/routes.jsx
  src/store/useAuthStore.js
Labels: 💻React

#90 fix: 상세 페이지 지도 초기값 문제 해결
  src/pages/content/ContentDetail.jsx
Labels: 💻React

#91 feat: 회원가입 유효성 검사 및 중복 확인 기능
  src/pages/Join.jsx
  src/utils/validation.js
Labels: 💻React, 💻기능추가

#92 댓글 전송 후 인풋 초기화 작업했습니다.
  src/components/content/AddComment.jsx
Labels: 💻React, 💻기능추가

#93 [기능 구현] 프로필 페이지 리스트 렌더링 등
  src/api/pocketbase.js
  src/components/ProfileComment.jsx
  src/components/content/ContentItem.jsx
  src/pages/MyProfile.jsx
  src/pages/content/ContentDetail.jsx
Labels: 💻React

#94 [기능 구현] 반응형 헤더, 여러 에러 핸들링
  package.json
  pnpm-lock.yaml
  src/components/header/Navigation.jsx
  src/components/header/NavigationCenter.jsx
  src/components/header/NavigationSide.jsx
  src/components/login/KakaoLogin.jsx
  src/layout/Header.jsx
  src/pages/content/ContentEdit.jsx
  tailwind.config.js
Labels: 💻HTML, 💻CSS, 💻React, 💻기능추가

#95 feat: 프로필 페이지 더보기 버튼 조건 처리
  src/components/TitleButton.jsx
  src/pages/MyProfile.jsx
Labels: 💻React

#96 [컴포넌트 수정] CSS Style 수정
  src/components/ProtectRoute.jsx
  src/components/header/Navigation.jsx
  src/components/join/Modal.jsx
  src/components/join/TermsOfService.jsx
  src/components/login/LoginPageContent.jsx
  src/layout/Header.jsx
  src/layout/RootLayout.jsx
  src/pages/Home.jsx
Labels: 💻HTML, 💻CSS

#106 댓글 추가, 수정, 삭제
  src/components/content/AddComment.jsx
  src/components/content/CommentItem.jsx
  src/components/weather/ImgSky.jsx
  src/pages/content/ContentDetail.jsx
  src/routes.jsx
Labels: 💻React, 💻기능추가

#107 프로필 페이지 기능 구현, 메인 페이지 슬라이드 효과 변경 등
  index.html
  public/favicon-96x96 2.png
  public/vite.svg
  src/assets/react.svg
  src/components/Logo.jsx
  src/components/MainSlide.jsx
  src/components/ProfileComment 2.jsx
  src/components/ScrollToTop.jsx
  src/components/TitleButton.jsx
  src/components/content/ContentItem.jsx
  src/components/profile/ProfileCommentSection.jsx
  src/components/profile/ProfileContentSection.jsx
  src/layout/Header.jsx
  src/layout/RootLayout.jsx
  src/pages/Contents.jsx
  src/pages/MyProfile.jsx
  src/pages/content/ContentCreate.jsx
Labels: 버그 수정, 💻React, 💻기능추가, 💻환경설정

#108 새로고침 이슈 해결, 상세 페이지 댓글 기능 최적화 등
  404.html
  index.html
  public/weather/partly_cloudy.svg
  src/components/Map.jsx
  src/components/content/CommentItem.jsx
  src/components/profile/ProfileCommentSection.jsx
  src/components/weather/ImgSky.jsx
Labels: 💻성능향상, 버그 수정, 💻React, 💻기능추가

#109 chore: 배포용 환경설정
  .github/workflows/deploy.yml
  package-lock.json
Labels: 버그 수정, 💻React, 💻기능추가, 💻환경설정

#119 메인페이지 페이지네이션, 태그 볼드 처리
  src/components/MainContent.jsx
  src/components/MainTag.jsx
  src/pages/Home.jsx
Labels: 💻React, 💻기능추가

#134 feat: 비로그인 시 댓글 작성 불가 알람
  src/components/content/AddComment.jsx
Labels: 💻React, 💻기능추가

#136 feat: 비밀번호 찾기 기능 구현 및 교통 페이지 기능 수정
  src/components/KakaoMap/GetKakaoMap.jsx
  src/components/join/PwEmail.jsx
  src/pages/finduser/FindPw.jsx
  src/routes.jsx
Labels: 💻React, 💻기능추가

#138 design: 날씨 페이지 폰트 크기 변경
  src/components/content/AddComment.jsx
  src/components/weather/ImgSky.jsx
  src/components/weather/ThreedaysWeatherTable.jsx
  src/components/weather/WeatherTable.jsx
Labels: 💻CSS

#139 fix: 카카오 로그인, useVerification 수정
  src/components/login/KakaoLogin.jsx
  src/hooks/useVerification.js
Labels: 버그 수정, 💻React

#140 아이디 찾기, 비밀번호 찾기,
  src/components/Button.jsx
  src/components/KakaoMap/GetKakaoMap.jsx
  src/components/content/AddComment.jsx
  src/components/join/PwEmail.jsx
  src/components/login/KakaoLogin.jsx
  src/components/weather/ImgSky.jsx
  src/components/weather/ThreedaysWeatherTable.jsx
  src/components/weather/WeatherTable.jsx
  src/hooks/useVerification.js
  src/layout/Header.jsx
  src/pages/finduser/FindId.jsx
  src/pages/finduser/FindPw.jsx
  src/routes.jsx
  vite.config.js
Labels: 💻CSS, 💻기능추가

#145 댓글에 시간 추가, 로그인 안했을 때 disabled, 날씨 warning 수정
  src/components/content/AddComment.jsx
  src/components/content/CommentItem.jsx
  src/components/weather/OnedayWeather.jsx
  src/components/weather/ThreedaysWeather.jsx
  src/pages/content/ContentDetail.jsx
Labels: 💻React, 💻기능추가

#148 [+α] 상세 페이지 리팩토링, 목록 페이지 레이아웃 변경 등
  404.html
  package-lock.json
  package.json
  public/pause_icon.svg
  public/play_icon.svg
  src/components/MainSlide.jsx
  src/components/Map.jsx
  src/components/ShowMap.jsx
  src/components/content/ContentItem.jsx
  src/components/profile/ProfileCommentSection.jsx
  src/components/profile/ProfileContentSection.jsx
  src/pages/Contents.jsx
  src/pages/Home.jsx
  src/pages/content/ContentDetail 2.jsx
  src/pages/content/ContentDetail.jsx
  src/store/usePageStore.js
Labels: 💻성능향상, 버그 수정, 💻CSS, 💻React, 💻환경설정

#151 모바일 화면 개선, import 오류 삭제 및 정리
  src/components/Map.jsx
  src/pages/content/ContentCreate.jsx
  src/pages/content/ContentDetail.jsx
  tailwind.config.js
Labels: 버그 수정, 💻CSS

#155 rename: 폴더 이름 변경 KakaoMap -> kakaomap
  src/components/KakaoMap/GetKakaoMap.jsx
  src/pages/Join.jsx
  src/pages/TrafficInfo.jsx
Labels: 💻CSS

#156 목록 페이지 페이지네이션 유지 및 지도 마커 클릭 시 리렌더링 방지 등
  src/components/Map.jsx
  src/components/content/ContentItem.jsx
  src/components/login/KakaoLogin.jsx
  src/components/profile/ProfileCommentSection.jsx
  src/components/profile/ProfileContentSection.jsx
  src/layout/RootLayout.jsx
  src/pages/Contents.jsx
  src/pages/content/ContentCreate.jsx
  src/routes.jsx
  src/store/usePageStore.js
  tailwind.config.js
Labels: 💻성능향상, 버그 수정, 💻React, 💻기능추가

#169 날씨 페이지 텐스텍쿼리 사용
  pnpm-lock.yaml
  src/components/weather/ImgSky.jsx
  src/components/weather/ThreedaysWeatherTable.jsx
  src/pages/WeatherInfo.jsx
Labels: 💻React, 💻기능추가

#171 helmet 메타데이터 추가 및 프로필 댓글 인피니트 쿼리 변경 등
  src/components/PageHead.jsx
  src/components/profile/ProfileCommentSection.jsx
  src/components/profile/ProfileContentSection.jsx
  src/pages/content/ContentDetail.jsx
Labels: 💻성능향상, 💻React, 💻기능추가

#173 Fix : 헤더 UX 개선, 로그인 한 사용자 접근 처리
  src/components/ProtectRoute.jsx
  src/components/ReplaceRoute.jsx
  src/components/login/KakaoLogin.jsx
  src/components/login/LoginPageContent.jsx
  src/layout/Header.jsx
  src/pages/Login.jsx
  src/pages/content/ContentEdit.jsx
  src/pages/finduser/FindId.jsx
  src/routes.jsx
Labels: 버그 수정, 💻React, 💻기능추가

#176 fix: 태그 재선택 문제 - 코드 수정
  src/pages/content/ContentEdit.jsx
Labels: 버그 수정

#178 fix: 태그 재선택 문제 - 코드 수정
  src/pages/content/ContentEdit.jsx
Labels: 버그 수정

#180 fix: 태그 재선택 문제
  src/pages/content/ContentEdit.jsx
Labels: 버그 수정

#182 fix: 수정 시 태그 재선택 문제
  src/pages/content/ContentEdit.jsx
  src/routes.jsx
Labels: 버그 수정

#184 fix: 태그 재선택 문제 수정
  src/pages/content/ContentEdit.jsx
Labels: 버그 수정

#186 feat: 회원가입 페이지 기능 추가
  src/components/Button.jsx
  src/components/join/Termscheck.jsx
  src/pages/Join.jsx
Labels: 도움 요청, 💻기능추가

#187 fix: 회원가입 중복 세분화, 게시글 삭제시 유저 테이블에서도 삭제
  src/pages/Join.jsx
  src/pages/content/ContentDetail.jsx
  src/pages/content/ContentEdit.jsx
Labels: 버그 수정, 💻기능추가

#188 fix: 아이디 input 안되는 현상 수정
  src/pages/Join.jsx
Labels: 버그 수정

#189 [리팩토링] 데이터 가져오는 함수 분리 및 페이지네이션 컴포넌트 분리
  src/components/PaginationButton.jsx
  src/components/profile/ProfileCommentSection.jsx
  src/components/profile/ProfileContentSection.jsx
  src/pages/Contents.jsx
  src/utils/fetchContents.js
Labels: 💻성능향상, 💻React

#191 메인 현제 페이지 버튼 색 , 댓글 버튼 크기, 닉네임 너비 수정
  src/components/MainContent.jsx
  src/components/content/AddComment.jsx
  src/components/content/CommentItem.jsx
  src/components/weather/SelectLocation.jsx
  src/components/weather/ThreedaysWeatherTable.jsx
  src/components/weather/WeatherTable.jsx
  src/pages/Home.jsx
  src/pages/WeatherInfo.jsx
  src/pages/content/ContentDetail.jsx
Labels: 💻React, 💻기능추가

#192 fix: 회원가입 중복확인 에러 수정
  src/components/login/LoginPageContent.jsx
  src/pages/Join.jsx
Labels: 버그 수정

#197 [기능 구현+] 모바일 뷰 최적화, 버그 수정 등
  src/App.jsx
  src/components/MainTag.jsx
  src/components/PaginationButton.jsx
  src/layout/RootLayout.jsx
  src/pages/Contents.jsx
  src/pages/Home.jsx
  src/pages/content/ContentCreate.jsx
  src/pages/content/ContentDetail.jsx
  src/pages/content/ContentEdit.jsx
Labels: 💻성능향상, 버그 수정, 💻CSS, 💻React, 💻기능추가

#203 [기능 구현+] 로그인, 회원 가입 페이지 모바일 뷰 최적화, 회원 가입 스페이스바 방지 등
  index.html
  src/components/Button.jsx
  src/components/InputField.jsx
  src/components/MainSlide.jsx
  src/components/MainTag.jsx
  src/components/join/Termscheck.jsx
  src/components/login/KakaoLogin.jsx
  src/components/login/LoginPageContent.jsx
  src/pages/Join.jsx
  src/pages/Login.jsx
  src/pages/content/ContentCreate.jsx
  tailwind.config.js
Labels: 💻성능향상, 버그 수정, 💻CSS

#207 style: 아이디 찾기, 비밀번호 찾기 페이지 모바일 뷰 최적화
  src/pages/finduser/FindId.jsx
  src/pages/finduser/FindPw.jsx
Labels: 💻성능향상, 💻CSS

#210 [기능 구현+] 페이지 제목 수정 및 교통 정보 메뉴 최솟값 부여
  src/components/kakaomap/GetKakaoMap.jsx
  src/layout/Header.jsx
  src/pages/Contents.jsx
  src/pages/Home.jsx
Labels: 💻CSS, 💻React

#213 README 작성 및 기본 댓글 이슈
  README.md
  src/components/profile/ProfileCommentSection.jsx
Labels: 📑문서, 버그 수정

#226 [기능 구현+] 헤더 접근성, 불투명도 수정, 목록 prefetch
  src/components/Map.jsx
  src/layout/Header.jsx
  src/pages/Contents.jsx
Labels: 💻성능향상

#228 [기능 구현+] 프로필 페이지 닉네임 수정 기능
  gitmessage.txt
  public/pen_edit.svg
  src/pages/Contents.jsx
  src/pages/MyProfile.jsx
Labels: 💻기능추가
